#!/usr/bin/env python

import sys

from scraper import scrap_match, scrap_summoner

if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.exit('No action selected, exiting')
    if '--match-id' in sys.argv:
        scrap_match(sys.argv[-1])
    if '--summoner-id' in sys.argv:
        scrap_summoner(sys.argv[2:] if len(sys.argv) > 2 else None)
